using Virtual_Assistant.Models;

namespace Virtual_Assistant;

public interface IChatHandler
{
    /// <summary>
    /// When the message is generated by the other party.
    /// </summary>
    event EventHandler<ChatMessage> CompleteMessageGenerated;

    event EventHandler<string> PartialMessageGenerated;

    public ChatChannel ChatChannel { get; set; }

    Task InitializeAsync();

    Task<string?> SendMessageAndGetResultAsync(ChatMessage message);
}